export const EDIT_GOALS_LIST = 'EDIT_GOALS_LIST';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING = 'LOADING';
export const LOADED = 'LOADED';
export const JWT_EXPIRED = 'JWT_EXPIRED';
export const LOGOUT = 'LOGOUT';
export const GET_GOALS_LIST = 'GET_GOALS_LIST';
export const UPDATE_GOALS_LIST = 'UPDATE_GOALS_LIST';
export const FETCH_SELECTED_GOAL = 'FETCH_SELECTED_GOAL';
export const DELETE_GOAL = 'DELETE_GOAL';
export const CREATE_ORDER = 'CREATE_ORDER';
export const REORDER = 'REORDER';
export const EXCLUDE_ELEMENT_FROM_ORDER = 'EXCLUDE_ELEMENT_FROM_ORDER';
export const ADD_ELEMENT_TO_ORDER = 'ADD_ELEMENT_TO_ORDER';

export const CHECK_UP_GOAL_DAY = 'CHECK_UP_GOAL_DAY';
